/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.enb.Userinterface;

import com.enb.ENBController.CheckRegistration;
import com.enb.ENBController.DataBaseConnection;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author mBk'
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setBounds(720, 250, 230, 30);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.setBounds(720, 110, 230, 30);
        jLayeredPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField3.setBounds(720, 180, 230, 30);
        jLayeredPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPasswordField1.setBounds(720, 390, 230, 30);
        jLayeredPane1.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPasswordField2.setBounds(720, 320, 230, 30);
        jLayeredPane1.add(jPasswordField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sup.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(720, 430, 80, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lgn.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(870, 440, 70, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg5.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 1100, 560);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1103, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fullname=jTextField2.getText();
        String username=jTextField1.getText();
        String password=jPasswordField1.getText().toString();

        String confirm=jPasswordField2.getText().toString();
        String email=jTextField3.getText();
       
       
        String gender="";
        String no="";
        Pattern p = Pattern.compile(".+@.+\\.[a-z]+");

                                    // Match the given string with the pattern
        Matcher m = p.matcher(email);
        boolean matchFound = m.matches();
        StringTokenizer st = new StringTokenizer(email, ".");
        String lastToken = null;
        while (st.hasMoreTokens()) 
        {
              lastToken = st.nextToken();
        }
            
  
  if(fullname.equalsIgnoreCase(no)|| username.equalsIgnoreCase(no) || password.equalsIgnoreCase(no)|| confirm.equalsIgnoreCase(no)
          || email.equalsIgnoreCase(no) )
  {
      JOptionPane.showMessageDialog(null,"Please enter the details which are missing");
                this.dispose();
                 new SignUp().setVisible(true);
  }
        
  else if (!(matchFound && lastToken.length() >= 2 && email.length() - 1 != lastToken.length())) 
  {                   
                JOptionPane.showMessageDialog(null,"Please enter correct email id");
                this.dispose();
                new SignUp().setVisible(true);// validate the country code
                                       
  }
  
           
               
  else if (!password.equals(confirm) )
  {
           System.out.println("password="+password);
           System.out.println("null="+no);
           JOptionPane.showMessageDialog(null,"Password and Confirm Password didn't match");
           this.dispose();
            new SignUp().setVisible(true);

  }
  
 else
  {
     
  try {
            // TODO add your handling code here:
            Connection conn;
            conn = (Connection) DataBaseConnection.dbConnection();
            String sql = "Select emai_id from registrations where user_name='" +username + "'" ;
            String sql1 = "Select emai_id from registrations where emai_id='" +email + "'" ;
            Statement stmt = (Statement) conn.createStatement();
            ResultSet rs = (ResultSet) stmt.executeQuery(sql);
            
            if (rs.next() ) {
               JOptionPane.showMessageDialog(null,"user name already exists");
               rs.close();
                this.dispose(); 
                 new SignUp().setVisible(true);
           
           
           
           }
          else {
                ResultSet rs1 = (ResultSet) stmt.executeQuery(sql1);
                if (rs1.next() ) {
               JOptionPane.showMessageDialog(null,"email id already exists"); rs1.close();
                this.dispose();
                 new SignUp().setVisible(true);
           } 
            
        }
           rs.close();
 
           
          
            
    
    System.out.println(fullname);
    System.out.println(username);
    System.out.println(password);
    System.out.println(confirm);
    System.out.println(email);
    System.out.println(gender);
 
    ArrayList details = new ArrayList();
    details.add(username);
    details.add(fullname);
    details.add(password);
    details.add(email);
    details.add(gender);
    details.add("");
    details.add("");
    try {            
    int status=CheckRegistration.Check_username(details);
    if (status==0){
        this.dispose(); //username already exists
       new SignUp().setVisible(true);
    }
    if (status==1){
        JOptionPane.showMessageDialog(null,"Successfully Registered..\n Please set security question in account..");
       // Add_to_Log.main(MainStarts.login_name, "Registered");
        this.dispose();
        
       new Account(username).setVisible(true);
        
    }
    
        } catch (Exception ex) {
            //Logger.getLogger(SignUpForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
                                          

  }   catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } 
  }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
